import Head from 'next/head'
import DragDropFile from '../components/fileupload'
import Navbar from '../components/navbar'

export default function Home() {
  return (
    <div className='h-screen flex flex-col'>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar/>
      <div className='flex h-5/6 justify-center items-center flex-col'>
        <h3 className=' text-3xl mb-3'>Welcome To zyx3d.xyz</h3>
        <p className='mb-10 text-gray-500'>Currently Support: .gltf, .obj, .glb</p>
        <DragDropFile/>
      </div>

    </div>
  )
}
