import Head from 'next/head'
import DragDropFile from '../components/fileupload'
import Navbar from '../components/navbar'

export default function Home() {
  return (
    <div className='h-screen flex flex-col'>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar/>
      <div className='flex h-full justify-center items-center flex-col w-full'>
        
        <DragDropFile/>
      </div>

    </div>
  )
}
